### ISSUE TITLE
多个worker进程的情况下，连接池失效的问题

### ISSUE THREAD

**Issue by lucasbozhi** [yangxikun/swoole2-mysqlpool#1]
楼主您好，我项目用到您这个模块
发现：
多个worker进程的情况下，连接池失效的问题
多个work的时候，由于不能正确获取到poolnum的数量，
连接池的resycle方法失效，导致连接越来越多

有什么好的解决方法吗

**Comment by yangxikun** [comment]
能贴个复现问题的代码出来吗？
还有复现步骤也说明下。
根据你的描述不是很理解你的意思

**Comment by lucasbozhi** [comment]
感谢回复
	static public function recycle(\Swoole\Coroutine\MySQL $conn)
	{
		echo "busyConns:".count(self::$busyConns)."\n";
		echo "spareConns:".count(self::$spareConns)."\n";
		echo "pendingFetchCount:".count(self::$pendingFetchCount)."\n";
		echo "resumeFetchCount:".count(self::$resumeFetchCount)."\n";
		echo "connsNameMap:".count(self::$connsNameMap)."\n";  
                echo "connsPool:".count(&self::$spareConns[$connName])."\n"; 

在这里加了调试信息，当worker数量为1时，链接池的的数量正常
当worker数量为多个时，连接池的数量为0，导致不能触发close
而3306的实际连接却越来越多，多到2000+
我只有300的测试并发

**Comment by yangxikun** [comment]
我测试了下没有问题哦，测试代码：
```php
<?php
require './swoole2-mysqlpool/MySQLPool.php';
use Swoole\Coroutine\Pool\MySQLPool;
$http = new swoole_http_server("127.0.0.1", 9501);
$http->on('request', function ($request, $response) {
        MySQLPool::init([
                        'test' => [
                                        'serverInfo' => ['host' => '172.17.0.2', 'user' => 'root', 'password' => 'my-secret-pw', 'database' => 'test', 'charset' => 'utf8'],
                                        'maxSpareConns' => 5,
                                        'maxConns' => 10
                        ],
        ]);
        $swoole_mysql = MySQLPool::fetch('test');
        $ret = $swoole_mysql->query('select sleep(1)');
        MySQLPool::recycle($swoole_mysql);
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");

});
$http->start();
```
压测：ab -s 900 -c 300 -n 900 http://127.0.0.1:9501/ 
压测结果：
Concurrency Level:      300
Time taken for tests:   23.095 seconds
Complete requests:      900
Failed requests:        0
Total transferred:      158400 bytes
HTML transferred:       25200 bytes
Requests per second:    38.97 [#/sec] (mean)
Time per request:       7698.257 [ms] (mean)
Time per request:       25.661 [ms] (mean, across all concurrent requests)
Transfer rate:          6.70 [Kbytes/sec] received

查看连接数（最多时达到40 = worker进程数*配置的maxConns）：netstat -anltp | grep 3306| grep ESTABLISHED | wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
40
压测结束查看连接数是20，符合预期。

PHP版本：5.6，swoole版本：最新master分支

**Comment by lucasbozhi** [comment]
实测是这边压力太大了，导致数据库链接过多，mysql配置是被重置了。。之前设置的是50000并发，报错时候只有1024，压力过大时直接堵死了mysql
