### ISSUE TITLE
WARNING swSignalfd_onSignal (ERRNO 707): Unable to find callback function for signal Broken pipe: 13

### ISSUE THREAD

**Issue by T200proX7** [yangxikun/swoole2-mysqlpool#3]
Hello,

i just want to notice that if your mysql timeout settings are too low.. you will receive the following error message: 

> WARNING swSignalfd_onSignal (ERRNO 707): Unable to find callback function for signal Broken pipe: 13

this message appears in situation you try to send data to a already closed connection.

### == Solution == 

**1. Mysql Settings:**
set your interactive and wait timeout of mysql very high.

OR

**2. Harden the MySQLPool.php:**
i checked the code and found `$conn->connected`:
$conn->connected is not reliable and my tests shows me that it is always =1 when you opened a connection onced. if the connection got closed from the server it still will be =1 .. 
`->connected` just get affected if the script itself close connection.

also the attributes ->connect_errno or ->connect_error are not affected when the mysql server close the connection due timeout. error and errno -> this will give you usable informations.

im not a **pro-**programmer but i think the solution for this is to not check against ->connected -> better use `$conn->ping(); ` but unfortunately this brings up a warning if the object is not available anymore. 

another possible solution is:
`if(is_resource($connection) && get_resource_type($connection)==='mysql link'){`

maybe would be good to take care of this situation and check if the connection got closed from the mysql server and if so .. remove it out of the pool or restart it.

the mysql server timeout can trigger in the `fetch `but also in the `recycle `prodecure.

regards

**Comment by yangxikun** [comment]
Sorry, this repo is no longer maintenance.
This repo is too old, based on swoole 2, but it had developed to swoole 4.
You can fork it and fix the problem.
